// ============================================================
// Builds the app's Character / Word data from the data modules
// ============================================================
//
// This used to read audio-manifest.json, which was generated by scanning the
// recorded MP3s — the filenames were the schema, so a character existed only
// if it had audio. Audio now comes from TTS keyed by text (see ttsAudio), so
// the data stands on its own: kana from kanaData.ts, kanji from data/kanji/*.

import type { Character, Reading } from '$lib/models/Character';
import type { Word } from '$lib/models/Word';
import { HIRAGANA_BASIC, KATAKANA_BASIC } from '$lib/data/kanaData';
import n5Kanji from '$lib/data/kanji/n5-kanji.json';
import n4Kanji from '$lib/data/kanji/n4-kanji.json';

/** One kanji as stored in data/kanji/*.json. */
export interface KanjiEntry {
  character: string;
  kun_yomi: string[];
  on_yomi: string[];
  meanings: string[];
  examples?: string[];
  words?: { word: string; reading: string; meaning: string }[];
}

export class DataLoader {
  private characters: Map<string, Character[]> = new Map();
  private wordsByLevel: Map<string, Word[]> = new Map([
    ['N5', []],
    ['N4', []]
  ]);
  private wordsByKanji: Map<string, Word[]> = new Map();

  loadAll(): void {
    // Basic gojuuon only — callers treat these lists as the "basic" category and
    // pull dakuten/youon from kanaData themselves, so including them here would
    // double-count them in the kana quiz.
    this.characters.set('hiragana', HIRAGANA_BASIC);
    this.characters.set('katakana', KATAKANA_BASIC);

    this.loadKanji('kanji_n5', 'N5', n5Kanji as KanjiEntry[]);
    this.loadKanji('kanji_n4', 'N4', n4Kanji as KanjiEntry[]);
  }

  private loadKanji(type: string, level: 'N5' | 'N4', entries: KanjiEntry[]): void {
    const chars: Character[] = entries.map((entry) => {
      const readings: Reading[] = [
        ...entry.kun_yomi.map((text): Reading => ({ text, readingType: 'kun' })),
        ...entry.on_yomi.map((text): Reading => ({ text, readingType: 'on' }))
      ];
      return {
        character: entry.character,
        characterType: type as Character['characterType'],
        meaning: entry.meanings[0] || undefined,
        jlptLevel: level,
        readings
      };
    });
    this.characters.set(type, chars);

    const levelWords = this.wordsByLevel.get(level) ?? [];
    for (const entry of entries) {
      const words: Word[] = (entry.words ?? [])
        .filter((w) => w.word && w.meaning)
        .map((w) => ({
          word: w.word,
          reading: w.reading,
          meaning: w.meaning,
          kanji: entry.character,
          jlptLevel: level
        }));

      if (words.length > 0) {
        this.wordsByKanji.set(entry.character, words);
        levelWords.push(...words);
      }
    }
    this.wordsByLevel.set(level, levelWords);
  }

  getCharacters(type: string): Character[] {
    return this.characters.get(type) ?? [];
  }

  getAllCharacters(): Map<string, Character[]> {
    return new Map(this.characters);
  }

  getWords(jlptLevel?: 'N5' | 'N4'): Word[] {
    if (!jlptLevel) {
      return [...(this.wordsByLevel.get('N5') ?? []), ...(this.wordsByLevel.get('N4') ?? [])];
    }
    return this.wordsByLevel.get(jlptLevel) ?? [];
  }

  getWordsByKanji(kanji: string): Word[] {
    return this.wordsByKanji.get(kanji) ?? [];
  }

  getWordsByLevels(levels: ('N5' | 'N4')[]): Word[] {
    return levels.flatMap((l) => this.wordsByLevel.get(l) ?? []);
  }
}
